services:
  proxy:
    image: nginx:latest
    network_mode: host
    restart: always
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/proxy.conf
      - ./etc/letsencrypt/live/timmciver.com/:/etc/letsencrypt/live/timmciver.com/

